### ISSUE TITLE
Bolt1.2: Some APP SDK samples in 2.9 are failing to build with respect to bolt 1.2 package.

### ISSUE THREAD

**Issue by jhkumar** [HSA-Libraries/Bolt#215]
When we try to build bolt samples of AMD APP SDK by linking to the bolt 1.2 package, two samples( BoxFilterSAT and Stockdataanalysis,) are failed to build by throwing compilation error.

**Comment by jhkumar** [comment]
This issue is not with the bolt but on APP SDK samples, also this should be opened anyhow in other forum.
